[project]
name = "year2021"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "sphinx-book-theme>=1.1.4",
    "sphinx>=7.4.7",
    "sphinxcontrib-tikz>=0.4.20",
]
